/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void restaurantTesting() {
        Restaurant KFC = new Restaurant("KFC", "55$");
        assertNotNull(KFC, "Check your class , it returned NULL");
        assertEquals("KFC", KFC.getName());
    }

    @Test
    void reviewTesting() {
        Restaurant KFC = new Restaurant("KFC", "$$");
        Review review1 = new Review("Food was delicious","Hamzeh",4);

        KFC.addReview(review1);


        assertNotNull(KFC, "Check your class , it returned NULL");

        assertEquals("[Reviewer : Hamzeh\n" +
                "Review : Food was delicious\n" +
                "Rating :  4 stars\n" +
                "]", KFC.getReviews().toString());


    }
}
