/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.DisplayName;

import java.util.ArrayList;

class LibraryTest {
    @Test
    void restaurantTesting() {
        Restaurant KFC = new Restaurant("KFC", "55$");
        assertNotNull(KFC, "Check your class , it returned NULL");
        assertEquals("KFC", KFC.getName());
    }

    class addReviewTest {
        @Test
        void addTest() {

            ArrayList<String> movieList = new ArrayList<>();
            movieList.add("the GodFather");
            movieList.add("Scarface");
            movieList.add("Fight Club");
            movieList.add("The Revenant");
            movieList.add("Shutter Island");

            Theater newTheater = new Theater("the Alpha", movieList);
//            Review review = new Review();
//            Review review1 = new Review();
            newTheater.addReview("Theater was good", "Hamzeh", 4);
            newTheater.addReview("Theater was good", "Hamzeh", 2);
            newTheater.addMovie("Shutter Island");
            newTheater.removeMovie("Fight Club");

            assertEquals("the Alpha", newTheater.getTheaterName());
            assertTrue(newTheater.getMovies().contains("Shutter Island"));
            assertFalse(newTheater.getMovies().contains("TENET"));
        }

        // test shop constructor
        class shopTest {
            @Test
            void shopToStringTest() {
                Shop shopTest = new Shop("PizzaHut", "Not Good ", 4);
                assertEquals(shopTest.toString(), "the review to PizzaHut not Good ");
            }
        }

        // add review to shop test
        class addReviewShopTest {
            @Test
            void addTest() {
                Shop revTest = new Shop("Popeyes", "Hamzeh", 2);
                revTest.addReview("l", "Hamzeh", 3);
                revTest.addReview("n", "Hamzeh", 2);
                revTest.addReview("Bad", "Hamzeh", 5);
                assertEquals(revTest.getShopRating(), (4));
            }
        }

        class addReviewTheaterTest {
            @Test
            void addTest() {
                ArrayList movies = new ArrayList();
                movies.add("the GodFather");
                movies.add("requiem for a dream");
                Theater revTest = new Theater("Cinema", movies);
                revTest.addReview("Bad", "hamzeh", 3);
                revTest.addReview("a", "hamzeh", 5);
                revTest.addReview("g", "hamzeh", 4);
                revTest.addMovie("taxi driver");
                ArrayList<String> y = new ArrayList<>();
                y.add("the GodFather");
                y.add("requiem for a dream");
                y.add("taxi driver");
                assertEquals(revTest.getMovies(), y);
            }

        }
    }
}



