/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void mappingTesting() {
        App classUnderTest = new App();
        int[][] array = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        assertNotNull(classUnderTest.mapping(array));
    }

    @Test
    void Tallying() {
        App classUnderTest = new App();
        List<String> votes = new ArrayList<>();
        votes.add("hamzeh");
        votes.add("hamzeh");
        votes.add("hamzeh");
        votes.add("hamzeh");
        votes.add("ahmad");
        votes.add("ahmad");
        votes.add("ahmad");
        votes.add("noor");
        votes.add("noor");

        String winner = classUnderTest.tally(votes);
    }
}